[package]
name = "rust-sample-api"
version = "0.1.0"
authors = ["Takashi Ishii <x-ishii@fujisan.co.jp>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
dotenv = "0.9.0"
chrono = "0.4.6"
